---
functional:
  - Пользователь может пройти регистрацию используя почту, аккаунт дискорд, гитхаб
  - Пользователь может авторизоваться используя почту, аккаунт дискорд, гитхаб и выйти из авторизации
  - В личном кабинете пользователя доступна информация профиля, настройки
  - Пользователь может создать игру с ботом, с человеком
  - Пользователь может отправлять сообщение в чат
non-functional:
  - Сайт должен быть доступен на мобильных устройствах
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (1000 пользователей)
  - Сайт должен быть оформлен в одном стиле во всех разделах
implicit:
  - Пользователь может удалить аккаунт
  - В личном кабинете пользователь может изменить аватар
  - Пользователь может устанавливать время игры
  - Пользователь может выбрать сложности игры
  - Пользователь может остановить игру или выйти
  - Пользователь может просмотреть запись игры
  - Пользователь может поделиться записью игры из страницы записи
  - Пользователь может выбрать рандомную игру. При выборе рандомной игры сложность определяется согласно выбранному уровню
  - Пользователь может посмотреть свой рейтинг, опыт, количество игр, количество побед/проигрышей
  - Пользователь может выбрать соперника (бот или человек)
  - Пользователь может создавать турнир
  - Пользователь может направить вызов сопернику
  - Пользователь может принять или отклонить вызов
