---
functional:
  - Пользователь может пройти регистрацию используя почту, аккаунт дискорд, гитхаб
  - Пользователь может авторизоваться используя почту, аккаунт дискорд, гитхаб и выйти из авторизации
  - В личном кабинете пользователя доступна информация профиля, настройки
  - Пользователь может создать игру с ботом, с человеком
  - Пользователь может выбрать сложности игры
  - Пользователь может подключиться к уже созданной игре в качестве игрока
  - Пользователь может подключиться к уже созданной игре в качестве зрителя
  - Пользователь может выбрать язык задачи русский или английский
  - Пользователь может отправлять сообщение в чат
  - В ходе игры пользователь может отключиться и повторно подключиться
  - Пользователь получает очки за победу в игре
  - Пользователь может посмотреть свой рейтинг, опыт, количество игр, количество побед/проигрышей
  - В ходе игры пользователь может проверять код неограниченное количество раз
  - При подтверждении правильности решения выводится сообщение с информацией о победителе
  - Победитель может выйти из игры по кнопке Exit
non-functional:
  - Сайт должен быть доступен на мобильных устройствах
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (1000 пользователей)
  - Сайт должен быть оформлен в одном стиле во всех разделах
implicit:
  - Пользователь может удалить аккаунт
  - В личном кабинете пользователь может изменить аватар
  - Пользователь может устанавливать время игры
  - Пользователь может остановить игру или выйти
  - Пользователь может просмотреть запись игры
  - Пользователь может поделиться записью игры из страницы записи
  - Пользователь может выбрать рандомную игру. При выборе рандомной игры сложность определяется согласно выбранному уровню
  - Пользователь может создавать турнир
  - Пользователь может направить вызов сопернику
  - Пользователь может принять или отклонить вызов
  - Пользователь может создать новую задачу (игру)
  - Пользователь может в ходе игры изменить выбранный язык программирования
  - Поьзователь может восстановить пароль с помощью email
